"""The take-off as the Ref.+Str. sheet itemises it, with rates.

Generated from 'Furnace costing _60TPH_BRF 12mtr.xlsx', Ref.+Str. rows 3-53.
Each row names the engine attribute its quantity comes from, whether that
quantity rounds up to a whole piece before it is billed (the sheet rounds
every one of them, which is why its L43 total sits a little above the raw
H79 the refractory block computes), the weight of one piece, and a rate from
each of the three vendors the workbook prices against.

basis says what the rate multiplies: 'each' a piece, 'kg' the line weight.
"""

# Ref.+Str. rows 3-42 — the refractory, priced three ways.
REFRACTORY_TAKEOFF = [
    dict(
        item='HANGING BRICK', material='60% High Alumina',
        place='ROOF', zone='SOAKING + HEATING',
        size='505 X 440 X 100 Thk.',
        qty_attr='hanging_bricks_soak_heat', roundup=True,
        wt_attr='hanging_brick_60_kg',
        basis='each',
        rate_trl=1483.0, rate_raj=1400.0, rate_bhil=1400.0,
    ),
    dict(
        item='HANGING BRICK', material='40% High Alumina',
        place='ROOF', zone='PREHEATING',
        size='505 X 440 X 100 Thk.',
        qty_attr='hanging_bricks_preheat', roundup=True,
        wt_attr='hanging_brick_40_kg',
        basis='each',
        rate_trl=1126.0, rate_raj=1350.0, rate_bhil=1350.0,
    ),
    dict(
        item='HOLDING BRICK', material='60% High Alumina',
        place='ROOF', zone='SOAKING + HEATING',
        size='405 X 305 X 100 Thk.',
        qty_attr='holding_bricks_soak_heat', roundup=True,
        wt_attr='holding_brick_60_kg',
        basis='each',
        rate_trl=904.0, rate_raj=880.0, rate_bhil=880.0,
    ),
    dict(
        item='HOLDING BRICK', material='40% High Alumina',
        place='ROOF', zone='PREHEATING',
        size='405 X 305 X 100 Thk.',
        qty_attr='holding_bricks_preheat', roundup=True,
        wt_attr='holding_brick_40_kg',
        basis='each',
        rate_trl=707.0, rate_raj=850.0, rate_bhil=850.0,
    ),
    dict(
        item='CERAMIC FIBRE', material='High Temp. Insulation',
        place='ROOF', zone='OVERALL ROOF',
        size='7300 X 600 X 25 Thk.',
        qty_attr='fibre_rolls', roundup=False,
        wt_attr='fibre_roll_kg',
        basis='each',
        rate_trl=2200.0, rate_raj=2200.0, rate_bhil=2200.0,
    ),
    dict(
        item='CASTABLE', material='INSULYTE',
        place='ROOF', zone='OVERALL ROOF',
        size='BAG OF 25 Kg',
        qty_attr='castable_bags', roundup=True,
        wt_attr='castable_bag_kg',
        basis='kg',
        rate_trl=60.0, rate_raj=52.0, rate_bhil=52.0,
    ),
    dict(
        item='FOIL', material='ALUMINIUM',
        place='ROOF', zone='OVERALL ROOF',
        size='1000 X 600 X 0.5 Thk.',
        qty_attr='foil_length_m', roundup=True,
        wt_attr='foil_piece_kg',
        basis='each',
        rate_trl=350.0, rate_raj=350.0, rate_bhil=350.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='RIGHT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='RIGHT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='60% FIRE BRICK', material='60% High Alumina',
        place='RIGHT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_fire_bricks_60', roundup=True,
        wt=5.0,
        basis='each',
        rate_trl=137.0, rate_raj=130.0, rate_bhil=125.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='RIGHT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='RIGHT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='40% FIRE BRICK', material='40% High Alumina',
        place='RIGHT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_fire_bricks_40', roundup=True,
        wt=4.3,
        basis='each',
        rate_trl=134.0, rate_raj=70.0, rate_bhil=59.0,
    ),
    dict(
        item='40% FIRE BRICK', material='40% High Alumina',
        place='RIGHT WALL', zone='Taper wall of PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='tapered_fire_bricks_40', roundup=True,
        wt=4.3,
        basis='each',
        rate_trl=134.0, rate_raj=70.0, rate_bhil=59.0,
    ),
    dict(
        item='BOARD', material='HEAISYL',
        place='RIGHT WALL', zone='OVERALL WALL',
        size='900 X 600 X 50Thk.',
        qty_attr='side_wall_hay_pieces', roundup=True,
        wt=8.0,
        basis='each',
        rate_trl=1230.0, rate_raj=1230.0, rate_bhil=1230.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='LEFT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='LEFT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='60% FIRE BRICK', material='60% High Alumina',
        place='LEFT WALL', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='side_wall_fire_bricks_60', roundup=True,
        wt=5.0,
        basis='each',
        rate_trl=137.0, rate_raj=130.0, rate_bhil=125.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='LEFT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='LEFT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='40% FIRE BRICK', material='40% High Alumina',
        place='LEFT WALL', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='preheat_fire_bricks_40', roundup=True,
        wt=4.3,
        basis='each',
        rate_trl=134.0, rate_raj=70.0, rate_bhil=59.0,
    ),
    dict(
        item='40% FIRE BRICK', material='40% High Alumina',
        place='LEFT WALL', zone='Taper wall of PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='tapered_fire_bricks_40', roundup=True,
        wt=4.3,
        basis='each',
        rate_trl=134.0, rate_raj=70.0, rate_bhil=59.0,
    ),
    dict(
        item='BOARD', material='HEAISYL',
        place='LEFT WALL', zone='OVERALL WALL',
        size='900 X 600 X 50Thk.',
        qty_attr='side_wall_hay_pieces', roundup=True,
        wt=8.0,
        basis='each',
        rate_trl=1230.0, rate_raj=1230.0, rate_bhil=1230.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='DISCHARGE', zone='DISCHARGE DOOR SIDE',
        size='230 X 115 X 75 Thk.',
        qty_attr='discharge_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='DISCHARGE', zone='DISCHARGE DOOR SIDE',
        size='230 X 115 X 75 Thk.',
        qty_attr='discharge_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='60% FIRE BRICK', material='60% High Alumina',
        place='DISCHARGE', zone='DISCHARGE DOOR SIDE',
        size='230 X 115 X 75 Thk.',
        qty_attr='discharge_fire_bricks_60', roundup=True,
        wt=5.0,
        basis='each',
        rate_trl=137.0, rate_raj=130.0, rate_bhil=125.0,
    ),
    dict(
        item='BOARD', material='HEAISYL',
        place='DISCHARGE', zone='DISCHARGE DOOR SIDE',
        size='900 X 600 X 50Thk.',
        qty_attr='discharge_hay_pieces', roundup=True,
        wt=8.0,
        basis='each',
        rate_trl=1230.0, rate_raj=1230.0, rate_bhil=1230.0,
    ),
    dict(
        item='C/F BRICK', material='COLD FACE',
        place='HEARTH', zone='OVERALL GROUND',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_cold_face_bricks', roundup=True,
        wt=1.8,
        basis='each',
        rate_trl=66.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='H/F BRICK', material='HOT FACE',
        place='HEARTH', zone='OVERALL GROUND',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_hot_face_bricks', roundup=True,
        wt=2.0,
        basis='each',
        rate_trl=124.0, rate_raj=70.0, rate_bhil=23.0,
    ),
    dict(
        item='IS - 8 BRICK', material='IS - 8',
        place='HEARTH', zone='OVERALL GROUND',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_is8_bricks', roundup=True,
        wt=3.8,
        basis='each',
        rate_trl=75.0, rate_raj=54.0, rate_bhil=55.0,
    ),
    dict(
        item='60% FIRE BRICK', material='60% High Alumina',
        place='HEARTH', zone='SOAKING',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_fire_bricks_60', roundup=True,
        wt=5.0,
        basis='each',
        rate_trl=137.0, rate_raj=130.0, rate_bhil=125.0,
    ),
    dict(
        item='50% FIRE BRICK', material='50% High Alumina',
        place='HEARTH', zone='SOAKING + HEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_fire_bricks_50', roundup=True,
        wt=4.8,
        basis='each',
        rate_trl=134.0, rate_raj=134.0, rate_bhil=134.0,
    ),
    dict(
        item='40% FIRE BRICK', material='40% High Alumina',
        place='HEARTH', zone='PREHEATING',
        size='230 X 115 X 75 Thk.',
        qty_attr='hearth_fire_bricks_40', roundup=True,
        wt=4.3,
        basis='each',
        rate_trl=134.0, rate_raj=134.0, rate_bhil=134.0,
    ),
    dict(
        item='BLOCK', material='BLOCK',
        place='DISCHARGE', zone='Single Lane Near Discharge door',
        size='600 X  200 X 150',
        qty_attr='block_lane_discharge', roundup=True,
        wt_attr='block_kg',
        basis='each',
        rate_trl=18000.0, rate_raj=4500.0, rate_bhil=4500.0,
    ),
    dict(
        item='BLOCK', material='BLOCK',
        place='DISCHARGE', zone='4 Lane in SOAKING + HEATING',
        size='600 X  200 X 150',
        qty_attr='block_lane_soaking', roundup=True,
        wt_attr='block_kg',
        basis='each',
        rate_trl=18000.0, rate_raj=4500.0, rate_bhil=4500.0,
    ),
    dict(
        item='CASTABLE', material='LC - 40',
        place='FLUE DUCT', zone='BEFORE RECUPERATOR 1',
        size='BAG OF 25 Kg',
        qty_attr='duct1_bags', roundup=True,
        wt=25.0,
        basis='kg',
        rate_trl=41.0, rate_raj=35.0, rate_bhil=35.0,
    ),
    dict(
        item='CASTABLE', material='LC - 40',
        place='FLUE DUCT', zone='AFTER RECUPERATOR 2',
        size='BAG OF 25 Kg',
        qty_attr='duct2_bags', roundup=True,
        wt=25.0,
        basis='kg',
        rate_trl=41.0, rate_raj=35.0, rate_bhil=35.0,
    ),
    dict(
        item='PASTE', material='ACCOSSET - 50',
        place='B/W BRICK', zone='ONLY FOR (60 + 50 + 40)% BRICK',
        size='BAG OF 50 Kg',
        qty_attr='take_off_accosset_qty', roundup=True,
        wt=50.0,
        basis='kg',
        rate_trl=17.3, rate_raj=14.0, rate_bhil=14.0,
    ),
    dict(
        item='PASTE', material='FIRECLAY',
        place='B/W BRICK', zone='ONLY FOR H/F & C/F BRICK',
        size='BAG OF 50 Kg',
        qty_attr='take_off_fireclay_qty', roundup=True,
        wt=50.0,
        basis='kg',
        rate_trl=15.3, rate_raj=9.0, rate_bhil=9.0,
    ),
    dict(
        item='CASTABLE', material='FIRECREAT',
        place='B/W GAPS', zone='Used only for Gaps Filling',
        size='BAG OF 50 Kg',
        qty_attr='take_off_firecreat_qty', roundup=True,
        wt=50.0,
        basis='kg',
        rate_trl=15.3, rate_raj=32.0, rate_bhil=32.0,
    ),
]

# Ref.+Str. rows 45-53 — the steel. One rate set only.
STRUCTURE_TAKEOFF = [
    dict(
        item='C-CHANNEL', material='MILD STEEL (IS-2062)',
        place='OUTER', zone='OVERALL FURNACE',
        size='250 X 80 X 7.5 Thk.',
        qty_attr='c_channel_total_m', roundup=True,
        wt_attr='c_channel_kg_per_m', wt_roundup=True,
        basis='kg',
        rate_trl=60.0,
    ),
    dict(
        item='I - BEAM', material='MILD STEEL (IS-2062)',
        place='ROOF', zone='OVERALL ROOF',
        size='350 X 180',
        qty_attr='beam_roof_total_m', roundup=True,
        wt=53.0,
        basis='kg',
        rate_trl=65.0,
    ),
    dict(
        item='I - BEAM', material='MILD STEEL (IS-2062)',
        place='ROOF', zone='OVERALL ROOF',
        size='200 X 100',
        qty_attr='beam_top_total_m', roundup=True,
        wt_attr='beam_tb_kg_per_m', wt_roundup=True,
        basis='kg',
        rate_trl=62.0,
    ),
    dict(
        item='I - BEAM', material='MILD STEEL (IS-2062)',
        place='BOTTOM', zone='OVERALL BOTTOM',
        size='350 X 140',
        qty_attr='beam_bottom_total_m', roundup=True,
        wt=53.0,
        basis='kg',
        rate_trl=62.0,
    ),
    dict(
        item='PLATE FOR JOINING', material='MILD STEEL (IS-2062)',
        place='ROOF', zone='OVERALL ROOF',
        size='250 X 200 X 12 Thk.',
        qty_attr='join_plate_count', roundup=True,
        wt_attr='beam_top_length_m', wt_roundup=True,
        basis='kg',
        rate_trl=55.0,
    ),
    dict(
        item='PLATE FOR WALLS', material='MILD STEEL (IS-2062)',
        place='SIDE WALLS', zone='OUTER BOX',
        size='1500 X 6300 X 8 Thk.',
        qty_attr='wall_plate_count', roundup=True, qty_x2=True,
        wt_attr='wall_plate_kg', wt_roundup=True,
        basis='kg',
        rate_trl=55.0,
    ),
    dict(
        item='PLATE FOR DOOR', material='MILD STEEL (IS-2062)',
        place='CHARGING', zone='CHARGING DOOR SIDE',
        size='7000 X 1000 X 16 Thk.',
        qty_attr='charge_door_kg', roundup=True,
        wt=1.0,
        basis='kg',
        rate_trl=55.0,
    ),
    dict(
        item='PLATE FOR WALLS', material='MILD STEEL (IS-2062)',
        place='DISCHARGE', zone='DISCHARGE DOOR SIDE',
        size='3000 X 8000 X 8 Thk.',
        qty_attr='discharge_plate_kg', roundup=True,
        wt=1.0,
        basis='kg',
        rate_trl=55.0,
    ),
    dict(
        item='PLATE FOR BOTTOM', material='MILD STEEL (IS-2062)',
        place='BOTTOM', zone='PLATE FO BOTTOM TIE ROD',
        size='8036 X 250 X 8 Thk.',
        qty_attr='tie_plate_kg', roundup=True,
        wt=1.0,
        basis='kg',
        rate_trl=55.0,
    ),
]

# Ref.+Str. N54 — a lump sum, not a weight.
PIPING_LUMP = 2000000.0
